apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smb8z7i5o-java-quarkus
  janus-idp.io/tekton: smb8z7i5o-java-quarkus
  backstage.io/kubernetes-id: smb8z7i5o-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smb8z7i5o-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
